<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MaxChemical.Logging\MaxChemical.Logging.csproj" />
	  <PackageReference Include="PetaPoco.Compiled" Version="6.0.441" />
	  <PackageReference Include="MySql.Data" Version="8.0.33" />
	  <PackageReference Include="System.Text.Json" Version="8.0.5" />
	  <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
	  <PackageReference Include="EPPlus" Version="6.2.10" />
  </ItemGroup>

</Project>
